# Generated by Django 5.1 on 2024-09-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.IntegerField(default=1)),
                ('device', models.CharField(default='cpu', max_length=10)),
            ],
        ),
    ]
